/* ============================================================================
   SafeRise -- js/saferise-poster.js
   prompt-galaxy-player.md -- the two-layer galaxy treatment for the guided-
   session player.

   Defines window.SRClearing = { mount(stage, audio, opts) }, the exact call
   shape js/sr-medplayer.js already invokes:

     if (root.SRClearing && root.SRClearing.mount) {
       root.SRClearing.mount(m.stage, m.audio, { warm: cfg.warm, cool: cfg.cool });
     }

   js/sr-medplayer.js is marked "supplied, not modified" (SR-393) and this
   pass's own brief never asks to touch it, so this file becomes the
   implementation behind the one extension point that already exists,
   rather than adding a second, competing mount path. It replaces
   js/sr-clearing-visual.js's abstract particle canvas; that file and its
   two <canvas class="sr-glow">/<canvas class="sr-field"> elements are left
   in place (still loaded, in case anything else ever calls SRClearing
   directly before this script), just hidden the moment this mounts.

   Depends on content/galaxy.js (GALAXY_POSTERS, generated by
   tools/mk_posters.py) having loaded first.

   ════════════════════════════════════════════
   THE GOVERNING RULE, ENFORCED IN JS TOO -- amended by
   prompt-galaxy-refinements.md #0, amended again by
   GALAXY-PLAYER-REFINEMENTS-v2.md #0
   ════════════════════════════════════════════
   This file never writes a `transform` inline style at all, on any
   element, ever -- every transform lives in a CSS keyframe or a computed
   `calc()`, not here. JS writes custom properties (--p, --amp, --release,
   --warmshift, --sr-ps-warm/-cool/-acc), a `playbackRate` on the subject/
   aura Animation objects (set once per mount now, not per tick -- v2 #1a
   holds the breath period for the whole session instead of ramping it),
   and an `animationName` selecting which of the three per-state keyframe
   variants runs (v2 #1b) -- never which property animates or by how much,
   so this still isn't writing a transform. The CSS keyframes themselves
   permit a translate on two elements beyond the five wander stars --
   .sr-ps-subject/.sr-ps-plain's `sr-ps-breatheA/U/N` and .sr-ps-aura's own
   `sr-ps-auraSwellA/U/N` -- each under ~1.8% of the frame, one element/one
   period/one curve each, per the amended rule. Section 7's verify step
   greps the emitted CSS for this. */

(function (root) {
  'use strict';

  var STEPS = ['Recognise', 'Regulate', 'Release', 'Rise'];
  var TICK_MS = 250; /* ~4Hz, per brief #4 -- --p does not need 60fps */

  function el(tag, cls) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    return n;
  }

  /* -------------------------------------------------- id from the audio src
     content/meditation.js's own rule: "the path lives here, never in
     markup", and audio filenames follow MEDITATION_BASE + '<id>-<slug>.mp3'.
     Extracting the id back out of audio.currentSrc is the only route
     available to this file, since js/sr-medplayer.js's build() never
     forwards cfg.key/cfg.id to SRClearing.mount() -- only warm/cool. */
  function idFromSrc(audio) {
    var src = audio.currentSrc || audio.src || '';
    var m = /\/(t\d-\d\d)-/.exec(src);
    return m ? m[1] : null;
  }

  function reducedMotion() {
    return root.matchMedia && root.matchMedia('(prefers-reduced-motion: reduce)').matches;
  }

  function warmShift() {
    var hr = new Date().getHours();
    return Math.max(0, Math.min(1, (hr - 8) / 14));
  }

  /* ---------------------------------------------------------- the breath
     GALAXY-PLAYER-REFINEMENTS-v2.md #1a/#1b -- two corrections to the
     original mockup, both rulings: the period is HELD for the whole
     session (no more easing every state toward a 10s target -- 10s is
     Agitated's own pair only, not a universal destination), and the peak
     keyframe position is per state (40% for Agitated's 4:6 ratio, 50% for
     Unsteady/Numb's even ratios). Source: the protocol's own `state`
     field in content/galaxy.js (GALAXY_POSTERS[id].state) -- read at mount
     time below, never `data-per` typed per player.

     Steady isn't in the brief's own table (it names Agitated/Unsteady/
     Numb only -- the three states that actually occur among the 30 track
     protocols; Steady only ever applies to t0-00). Judgment call, reported
     rather than silently assumed: Steady's own target has always been
     "4-in 6-out, already there" (SR-403's original framing) -- the same
     10s/40%-peak shape as Agitated -- so it reuses the 'A' keyframe/8
     held-seconds-map entry rather than inventing a fourth pair. */
  var STATE_HELD_BREATH = { Agitated: 10, Unsteady: 12, Numb: 8, Steady: 10 };
  var STATE_KEYFRAME = { Agitated: 'A', Unsteady: 'U', Numb: 'N', Steady: 'A' };

  /* Still Animation.playbackRate, never a duration rewrite (brief #1a: "The
     entrainment mechanism does not otherwise change"). The only change
     from SR-403/405's version is that this now runs ONCE, at mount, rather
     than every tick -- there is nothing left to ramp once the period is
     held for the whole session. Each CSS keyframe's own duration stays
     fixed at 10s regardless of which named variant is selected (see
     css/saferise-poster.css), so rate = 10 / heldSeconds reaches the true
     per-state period exactly once, with no phase jump. */
  function applyHeldBreath(elements, heldSeconds) {
    var rate = 10 / heldSeconds;
    elements.forEach(function (el) {
      if (!el || !el.getAnimations) return;
      var list = el.getAnimations();
      if (list.length) list[0].playbackRate = rate;
    });
    return rate;
  }

  /* ---------------------------------------------------------- audio aura
     One AnalyserNode per player, created on first play, its *analyser
     branch* disconnected on pause (source stays connected to destination
     throughout, or playback would go silent the moment Web Audio takes
     the routing over). Smoothed with a simple exponential moving average
     over the time-domain RMS -- reads as breath, not a level meter, per
     the brief's own instruction not to feed a raw FFT bin. */
  function makeAura(audio) {
    var ctx = null, analyser = null, source = null, data = null, smoothed = 0, connected = false;
    function ensure() {
      if (ctx) return;
      var Ctx = root.AudioContext || root.webkitAudioContext;
      if (!Ctx) return;
      ctx = new Ctx();
      source = ctx.createMediaElementSource(audio);
      analyser = ctx.createAnalyser();
      analyser.fftSize = 512;
      data = new Uint8Array(analyser.fftSize);
      source.connect(ctx.destination); /* always -- keeps audio audible */
    }
    function connectAnalyser() {
      ensure();
      if (!ctx || connected) return;
      source.connect(analyser);
      connected = true;
    }
    function disconnectAnalyser() {
      if (!connected) return;
      try { source.disconnect(analyser); } catch (e) {}
      connected = false;
    }
    function read() {
      if (!connected || !analyser) return smoothed;
      analyser.getByteTimeDomainData(data);
      var sum = 0;
      for (var i = 0; i < data.length; i++) {
        var v = (data[i] - 128) / 128;
        sum += v * v;
      }
      var rms = Math.sqrt(sum / data.length); /* 0..~1 */
      smoothed += (rms - smoothed) * 0.25; /* EMA, not a raw bin */
      return Math.max(0, Math.min(1, smoothed * 2.2));
    }
    function teardown() {
      disconnectAnalyser();
      if (ctx) { try { ctx.close(); } catch (e) {} }
    }
    return { connectAnalyser: connectAnalyser, disconnectAnalyser: disconnectAnalyser, read: read, teardown: teardown };
  }

  /* v2 #4 -- "One component owns its own controls." Built only when the
     caller opts in (opts.buildControl); js/sr-medplayer.js's own call
     never does, so the modal context (which already has
     .sr-medplayer__play) is unaffected. Real <button>, so it is keyboard-
     reachable and gets :focus-visible with no extra wiring; aria-label
     kept in sync with play/pause. Disabled (no click handler bound at
     all, not just visually) when hasAudio is false -- honest state, per
     SR-406, not a fake control. */
  function buildCtrl(stage, audio, hasAudio) {
    var ctrl = el('button', 'sr-ps-ctrl');
    ctrl.type = 'button';
    ctrl.appendChild(el('i'));
    stage.appendChild(ctrl);

    if (!hasAudio) {
      ctrl.disabled = true;
      ctrl.setAttribute('aria-disabled', 'true');
      ctrl.setAttribute('aria-label', 'Guided audio not yet available for this protocol');
      return ctrl;
    }

    ctrl.setAttribute('aria-label', 'Play guided audio');
    ctrl.addEventListener('click', function () {
      if (audio.paused) audio.play().catch(function () {});
      else audio.pause();
    });
    audio.addEventListener('play', function () {
      ctrl.setAttribute('data-playing', 'true');
      ctrl.setAttribute('aria-label', 'Pause guided audio');
    });
    audio.addEventListener('pause', function () {
      ctrl.removeAttribute('data-playing');
      ctrl.setAttribute('aria-label', 'Play guided audio');
    });
    audio.addEventListener('ended', function () {
      ctrl.removeAttribute('data-playing');
      ctrl.setAttribute('aria-label', 'Play guided audio');
    });
    return ctrl;
  }

  function buildPlainFallback(stage, data) {
    var img = el('img', 'sr-ps-plain');
    img.src = data.cover;
    img.alt = '';
    stage.insertBefore(img, stage.firstChild);
    return { subject: img };
  }

  function buildGalaxy(stage, data) {
    var frag = document.createDocumentFragment();

    var field = el('img', 'sr-ps-field'); field.src = data.field; field.alt = '';
    var clear = el('img', 'sr-ps-clear'); clear.src = data.clear; clear.alt = '';
    var lights = el('div', 'sr-ps-lights');
    var wander = el('div', 'sr-ps-wander');
    for (var i = 0; i < 5; i++) wander.appendChild(el('i'));
    var subjwrap = el('div', 'sr-ps-subjwrap');
    var subject = el('img', 'sr-ps-subject'); subject.src = data.subject; subject.alt = '';
    subjwrap.appendChild(subject);
    /* prompt-galaxy-refinements.md #2 -- .sr-ps-aura is now a wrapper only
       (carries the breath-synced sr-ps-auraSwell keyframe); the visible
       gradient plus the --amp/--release-responsive scale live on the inner
       div. See css/saferise-poster.css for why one element can't hold both. */
    var aura = el('div', 'sr-ps-aura');
    var auraInner = el('div', 'sr-ps-aura-inner');
    aura.appendChild(auraInner);
    var stepnow = el('p', 'sr-ps-stepnow');
    var edge = el('div', 'sr-ps-edge');

    [field, clear, lights, wander, subjwrap, aura, stepnow, edge].forEach(function (n) { frag.appendChild(n); });
    stage.insertBefore(frag, stage.firstChild);

    return { field: field, clear: clear, subject: subject, aura: aura, auraInner: auraInner, stepnow: stepnow, edge: edge };
  }

  function mount(stage, audio, opts) {
    opts = opts || {};

    /* hide the old particle canvases rather than removing them -- see file
       header */
    var oldGlow = stage.querySelector('canvas.sr-glow');
    var oldField = stage.querySelector('canvas.sr-field');
    if (oldGlow) oldGlow.style.display = 'none';
    if (oldField) oldField.style.display = 'none';

    stage.classList.add('sr-ps-stage');

    /* SR-406 · opts.id lets a caller name the protocol explicitly, for the
       case this pass exists to cover: a page that wants the poster mounted
       before any real audio (and therefore any parseable audio.src) exists
       at all. idFromSrc() stays the default so the one already-working
       caller (dashboard.html, via a real <audio src>) needs no change. */
    var id = opts.id || idFromSrc(audio);
    var data = (root.GALAXY_POSTERS && id) ? root.GALAXY_POSTERS[id] : null;

    var warm = (data && data.warm) || opts.warm || [212, 168, 103];
    var cool = (data && data.cool) || opts.cool || [124, 178, 196];
    stage.style.setProperty('--sr-ps-warm', warm.join(','));
    stage.style.setProperty('--sr-ps-cool', cool.join(','));
    stage.style.setProperty('--warmshift', warmShift().toFixed(2));

    var stateAccent = {
      Agitated: 'rgba(201,122,90,.30)', Unsteady: 'rgba(212,168,67,.26)',
      Numb: 'rgba(90,107,132,.32)', Steady: 'rgba(127,168,140,.30)'
    };
    if (data && stateAccent[data.state]) {
      stage.style.setProperty('--sr-ps-acc', stateAccent[data.state]);
    }

    /* v2 #1a -- read straight from the protocol's own state, not a
       per-player data-per attribute. Falls back to 'Agitated' only when
       the id genuinely isn't in the manifest at all (never expected in
       practice -- all 31 ids resolve, confirmed in this pass's own
       report), so there is always a valid keyframe/held-seconds pair. */
    var state = (data && data.state) || 'Agitated';
    var heldBreath = STATE_HELD_BREATH[state] || 10;
    var keyframeSuffix = STATE_KEYFRAME[state] || 'A';
    var reduced = reducedMotion();

    var layers, subjectEl;
    if (data && !data.flagged && data.field && data.clear && data.subject) {
      layers = buildGalaxy(stage, data);
      subjectEl = layers.subject;
    } else {
      /* flagged, or no manifest entry at all (id not recognised, or no
         audio-derivable id yet) -- plain poster + breath only, per #2 */
      var cover = (data && data.cover) || opts.fallbackCover;
      if (!cover) return { destroy: function () {} }; /* nothing to show */
      layers = buildPlainFallback(stage, { cover: cover });
      subjectEl = layers.subject;
    }

    /* v2 #1b -- select the per-state keyframe on both the subject/plain
       and the aura wrapper (same shape, same period -- v2 #2). Set before
       reading getAnimations() below so the Animation object returned is
       the one actually running under the chosen name. */
    if (subjectEl) subjectEl.style.animationName = 'sr-ps-breathe' + keyframeSuffix;
    if (layers.aura) layers.aura.style.animationName = 'sr-ps-auraSwell' + keyframeSuffix;

    if (!reduced) applyHeldBreath([subjectEl, layers.aura].filter(Boolean), heldBreath);
    /* Inspectable record of the held value -- not read by anything here
       (playbackRate above is what actually drives speed), but set once,
       never rewritten, so a computed-style check can confirm the period
       equals the state's own pair throughout the session and never drifts. */
    stage.style.setProperty('--breath', heldBreath.toFixed(2) + 's');

    var hasAudio = !!(audio.getAttribute && audio.getAttribute('src'));
    if (opts.buildControl) buildCtrl(stage, audio, hasAudio);

    var aura = makeAura(audio);

    var raf = null, lastTick = 0, running = false;

    function frame(now) {
      raf = null;
      if (!running) return;
      if (!document.contains(stage)) { teardown(); return; }
      if (now - lastTick >= TICK_MS) {
        lastTick = now;
        var dur = audio.duration;
        var p = (dur && isFinite(dur) && dur > 0) ? Math.max(0, Math.min(1, audio.currentTime / dur)) : 0;
        stage.style.setProperty('--p', p.toFixed(4));

        var idx = Math.min(3, Math.floor(p * 4));
        var within = (p * 4) - idx;
        if (layers.stepnow) {
          var name = STEPS[idx];
          if (layers.stepnow.textContent !== name) layers.stepnow.textContent = name;
        }
        var release = (idx === 2) ? Math.sin(within * Math.PI) : 0;
        stage.style.setProperty('--release', release.toFixed(3));

        if (!reduced) {
          stage.style.setProperty('--amp', aura.read().toFixed(3));
        }
      }
      raf = requestAnimationFrame(frame);
    }

    function start() {
      if (running) return;
      running = true;
      stage.setAttribute('data-sr-ps-playing', 'true');
      if (!reduced) aura.connectAnalyser();
      lastTick = 0;
      raf = requestAnimationFrame(frame);
    }
    function stop() {
      running = false;
      stage.setAttribute('data-sr-ps-playing', 'false');
      if (raf) cancelAnimationFrame(raf);
      raf = null;
      aura.disconnectAnalyser();
    }
    function reset() {
      stage.style.setProperty('--p', 0);
      stage.style.setProperty('--release', 0);
      if (layers.stepnow) layers.stepnow.textContent = '';
    }

    audio.addEventListener('play', start);
    audio.addEventListener('pause', stop);
    audio.addEventListener('ended', function () { stop(); reset(); });

    /* off-screen: SR-343's own pattern (js/saferise-track.js) -- a
       continuously-toggling IntersectionObserver, not a scroll listener,
       animation-play-state via a class rather than unobserving. */
    var io = null;
    if ('IntersectionObserver' in root) {
      io = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          stage.classList.toggle('sr-ps-off', !e.isIntersecting);
        });
      }, { threshold: 0.12, rootMargin: '0px 0px -8% 0px' });
      io.observe(stage);
    }

    function teardown() {
      stop();
      audio.removeEventListener('play', start);
      audio.removeEventListener('pause', stop);
      if (io) io.disconnect();
      aura.teardown();
    }

    /* No explicit destroy hook reaches this file from sr-medplayer.js's own
       close(), so self-check on the next tick after any play/pause churn;
       already covered inside frame() via document.contains(stage). */

    return { destroy: teardown };
  }

  root.SRClearing = { mount: mount };
})(window);
