/* ============================================================================
   SafeRise -- js/saferise-poster.js
   prompt-galaxy-player.md -- the two-layer galaxy treatment for the guided-
   session player.

   Defines window.SRClearing = { mount(stage, audio, opts) }, the exact call
   shape js/sr-medplayer.js already invokes:

     if (root.SRClearing && root.SRClearing.mount) {
       root.SRClearing.mount(m.stage, m.audio, { warm: cfg.warm, cool: cfg.cool });
     }

   js/sr-medplayer.js is marked "supplied, not modified" (SR-393) and this
   pass's own brief never asks to touch it, so this file becomes the
   implementation behind the one extension point that already exists,
   rather than adding a second, competing mount path. It replaces
   js/sr-clearing-visual.js's abstract particle canvas; that file and its
   two <canvas class="sr-glow">/<canvas class="sr-field"> elements are left
   in place (still loaded, in case anything else ever calls SRClearing
   directly before this script), just hidden the moment this mounts.

   Depends on content/galaxy.js (GALAXY_POSTERS, generated by
   tools/mk_posters.py) having loaded first.

   ════════════════════════════════════════════
   THE GOVERNING RULE, ENFORCED IN JS TOO -- amended by
   prompt-galaxy-refinements.md #0
   ════════════════════════════════════════════
   This file never writes a `transform` inline style at all, on any
   element, ever -- every transform lives in a CSS keyframe or a computed
   `calc()`, not here. JS only ever writes custom properties (--p, --breath,
   --amp, --release, --warmshift) plus a playbackRate on the existing
   breathe animation. The CSS keyframes themselves now permit a translate
   on two elements beyond the five wander stars -- .sr-ps-subject/
   .sr-ps-plain's shared `sr-ps-breathe` and .sr-ps-aura's own
   `sr-ps-auraSwell` -- both under ~1.8% of the frame, one element/one
   period/one curve each, per the amended rule. Section 5's verify step
   greps the emitted CSS for this. */

(function (root) {
  'use strict';

  var STEPS = ['Recognise', 'Regulate', 'Release', 'Rise'];
  var TICK_MS = 250; /* ~4Hz, per brief #4 -- --p does not need 60fps */

  function el(tag, cls) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    return n;
  }

  /* -------------------------------------------------- id from the audio src
     content/meditation.js's own rule: "the path lives here, never in
     markup", and audio filenames follow MEDITATION_BASE + '<id>-<slug>.mp3'.
     Extracting the id back out of audio.currentSrc is the only route
     available to this file, since js/sr-medplayer.js's build() never
     forwards cfg.key/cfg.id to SRClearing.mount() -- only warm/cool. */
  function idFromSrc(audio) {
    var src = audio.currentSrc || audio.src || '';
    var m = /\/(t\d-\d\d)-/.exec(src);
    return m ? m[1] : null;
  }

  function reducedMotion() {
    return root.matchMedia && root.matchMedia('(prefers-reduced-motion: reduce)').matches;
  }

  function warmShift() {
    var hr = new Date().getHours();
    return Math.max(0, Math.min(1, (hr - 8) / 14));
  }

  /* ---------------------------------------------------- breath entrainment
     Report (brief #5): changing animation-duration (or a CSS var it reads)
     on a *running* animation recomputes "how far into the cycle" as
     elapsed/duration, which snaps the visible phase the instant duration
     changes -- confirmed as the naive approach the brief warns about, not
     assumed. Instead each CSS keyframe's own duration is fixed at 10s
     (.sr-ps-subject/.sr-ps-plain's sr-ps-breathe, .sr-ps-aura's own
     sr-ps-auraSwell) and this file adjusts each *running* Animation
     object's playbackRate via the Web Animations API in lockstep:
     playbackRate = 10 / desiredPeriod. That changes speed continuously
     against the same timeline, with no phase jump and no restart -- the
     technique the brief is asking to be named, not merely a var rewrite.

     prompt-galaxy-refinements.md #2 asks the aura to share "the same
     period and curve" as the subject -- driving both Animation objects
     from the one playbackRate below is how that happens without a second,
     independent (and possibly drifting) driver. */
  function makeBreathDriver(elements, startPeriod) {
    var anims = [];
    elements.forEach(function (el) {
      if (!el || !el.getAnimations) return;
      var list = el.getAnimations();
      if (list.length) anims.push({ el: el, anim: list[0] });
    });
    function set(p) {
      var period = startPeriod + (10 - startPeriod) * Math.pow(p, 0.7);
      var rate = 10 / period;
      if (anims.length) {
        anims.forEach(function (a) { a.anim.playbackRate = rate; });
      } else {
        /* No Web Animations API (very old browser) -- fall back to the
           naive var rewrite on the first element only. It will stutter,
           per the brief's own warning; there is no better option without
           getAnimations(). */
        if (elements[0]) elements[0].style.setProperty('--breath', period.toFixed(2) + 's');
      }
      return period;
    }
    return { set: set };
  }

  /* ---------------------------------------------------------- audio aura
     One AnalyserNode per player, created on first play, its *analyser
     branch* disconnected on pause (source stays connected to destination
     throughout, or playback would go silent the moment Web Audio takes
     the routing over). Smoothed with a simple exponential moving average
     over the time-domain RMS -- reads as breath, not a level meter, per
     the brief's own instruction not to feed a raw FFT bin. */
  function makeAura(audio) {
    var ctx = null, analyser = null, source = null, data = null, smoothed = 0, connected = false;
    function ensure() {
      if (ctx) return;
      var Ctx = root.AudioContext || root.webkitAudioContext;
      if (!Ctx) return;
      ctx = new Ctx();
      source = ctx.createMediaElementSource(audio);
      analyser = ctx.createAnalyser();
      analyser.fftSize = 512;
      data = new Uint8Array(analyser.fftSize);
      source.connect(ctx.destination); /* always -- keeps audio audible */
    }
    function connectAnalyser() {
      ensure();
      if (!ctx || connected) return;
      source.connect(analyser);
      connected = true;
    }
    function disconnectAnalyser() {
      if (!connected) return;
      try { source.disconnect(analyser); } catch (e) {}
      connected = false;
    }
    function read() {
      if (!connected || !analyser) return smoothed;
      analyser.getByteTimeDomainData(data);
      var sum = 0;
      for (var i = 0; i < data.length; i++) {
        var v = (data[i] - 128) / 128;
        sum += v * v;
      }
      var rms = Math.sqrt(sum / data.length); /* 0..~1 */
      smoothed += (rms - smoothed) * 0.25; /* EMA, not a raw bin */
      return Math.max(0, Math.min(1, smoothed * 2.2));
    }
    function teardown() {
      disconnectAnalyser();
      if (ctx) { try { ctx.close(); } catch (e) {} }
    }
    return { connectAnalyser: connectAnalyser, disconnectAnalyser: disconnectAnalyser, read: read, teardown: teardown };
  }

  function buildPlainFallback(stage, data) {
    var img = el('img', 'sr-ps-plain');
    img.src = data.cover;
    img.alt = '';
    stage.insertBefore(img, stage.firstChild);
    return { subject: img };
  }

  function buildGalaxy(stage, data) {
    var frag = document.createDocumentFragment();

    var field = el('img', 'sr-ps-field'); field.src = data.field; field.alt = '';
    var clear = el('img', 'sr-ps-clear'); clear.src = data.clear; clear.alt = '';
    var lights = el('div', 'sr-ps-lights');
    var wander = el('div', 'sr-ps-wander');
    for (var i = 0; i < 5; i++) wander.appendChild(el('i'));
    var subjwrap = el('div', 'sr-ps-subjwrap');
    var subject = el('img', 'sr-ps-subject'); subject.src = data.subject; subject.alt = '';
    subjwrap.appendChild(subject);
    /* prompt-galaxy-refinements.md #2 -- .sr-ps-aura is now a wrapper only
       (carries the breath-synced sr-ps-auraSwell keyframe); the visible
       gradient plus the --amp/--release-responsive scale live on the inner
       div. See css/saferise-poster.css for why one element can't hold both. */
    var aura = el('div', 'sr-ps-aura');
    var auraInner = el('div', 'sr-ps-aura-inner');
    aura.appendChild(auraInner);
    var stepnow = el('p', 'sr-ps-stepnow');
    var edge = el('div', 'sr-ps-edge');

    [field, clear, lights, wander, subjwrap, aura, stepnow, edge].forEach(function (n) { frag.appendChild(n); });
    stage.insertBefore(frag, stage.firstChild);

    return { field: field, clear: clear, subject: subject, aura: aura, auraInner: auraInner, stepnow: stepnow, edge: edge };
  }

  function mount(stage, audio, opts) {
    opts = opts || {};

    /* hide the old particle canvases rather than removing them -- see file
       header */
    var oldGlow = stage.querySelector('canvas.sr-glow');
    var oldField = stage.querySelector('canvas.sr-field');
    if (oldGlow) oldGlow.style.display = 'none';
    if (oldField) oldField.style.display = 'none';

    stage.classList.add('sr-ps-stage');

    /* SR-406 · opts.id lets a caller name the protocol explicitly, for the
       case this pass exists to cover: a page that wants the poster mounted
       before any real audio (and therefore any parseable audio.src) exists
       at all. idFromSrc() stays the default so the one already-working
       caller (dashboard.html, via a real <audio src>) needs no change. */
    var id = opts.id || idFromSrc(audio);
    var data = (root.GALAXY_POSTERS && id) ? root.GALAXY_POSTERS[id] : null;

    var warm = (data && data.warm) || opts.warm || [212, 168, 103];
    var cool = (data && data.cool) || opts.cool || [124, 178, 196];
    stage.style.setProperty('--sr-ps-warm', warm.join(','));
    stage.style.setProperty('--sr-ps-cool', cool.join(','));
    stage.style.setProperty('--warmshift', warmShift().toFixed(2));

    var stateAccent = {
      Agitated: 'rgba(201,122,90,.30)', Unsteady: 'rgba(212,168,67,.26)',
      Numb: 'rgba(90,107,132,.32)', Steady: 'rgba(127,168,140,.30)'
    };
    if (data && stateAccent[data.state]) {
      stage.style.setProperty('--sr-ps-acc', stateAccent[data.state]);
    }

    var startBreath = (data && data.startBreath) || 10;
    var reduced = reducedMotion();

    var layers, subjectEl;
    if (data && !data.flagged && data.field && data.clear && data.subject) {
      layers = buildGalaxy(stage, data);
      subjectEl = layers.subject;
    } else {
      /* flagged, or no manifest entry at all (id not recognised, or no
         audio-derivable id yet) -- plain poster + breath only, per #2 */
      var cover = (data && data.cover) || opts.fallbackCover;
      if (!cover) return { destroy: function () {} }; /* nothing to show */
      layers = buildPlainFallback(stage, { cover: cover });
      subjectEl = layers.subject;
    }

    var breathDriver = reduced
      ? null
      : makeBreathDriver([subjectEl, layers.aura].filter(Boolean), startBreath);
    var aura = makeAura(audio);

    var raf = null, lastTick = 0, running = false;

    function frame(now) {
      raf = null;
      if (!running) return;
      if (!document.contains(stage)) { teardown(); return; }
      if (now - lastTick >= TICK_MS) {
        lastTick = now;
        var dur = audio.duration;
        var p = (dur && isFinite(dur) && dur > 0) ? Math.max(0, Math.min(1, audio.currentTime / dur)) : 0;
        stage.style.setProperty('--p', p.toFixed(4));

        if (breathDriver) breathDriver.set(p);

        var idx = Math.min(3, Math.floor(p * 4));
        var within = (p * 4) - idx;
        if (layers.stepnow) {
          var name = STEPS[idx];
          if (layers.stepnow.textContent !== name) layers.stepnow.textContent = name;
        }
        var release = (idx === 2) ? Math.sin(within * Math.PI) : 0;
        stage.style.setProperty('--release', release.toFixed(3));

        if (!reduced) {
          stage.style.setProperty('--amp', aura.read().toFixed(3));
        }
      }
      raf = requestAnimationFrame(frame);
    }

    function start() {
      if (running) return;
      running = true;
      stage.setAttribute('data-sr-ps-playing', 'true');
      if (!reduced) aura.connectAnalyser();
      lastTick = 0;
      raf = requestAnimationFrame(frame);
    }
    function stop() {
      running = false;
      stage.setAttribute('data-sr-ps-playing', 'false');
      if (raf) cancelAnimationFrame(raf);
      raf = null;
      aura.disconnectAnalyser();
    }
    function reset() {
      stage.style.setProperty('--p', 0);
      stage.style.setProperty('--release', 0);
      if (layers.stepnow) layers.stepnow.textContent = '';
    }

    audio.addEventListener('play', start);
    audio.addEventListener('pause', stop);
    audio.addEventListener('ended', function () { stop(); reset(); });

    /* off-screen: SR-343's own pattern (js/saferise-track.js) -- a
       continuously-toggling IntersectionObserver, not a scroll listener,
       animation-play-state via a class rather than unobserving. */
    var io = null;
    if ('IntersectionObserver' in root) {
      io = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          stage.classList.toggle('sr-ps-off', !e.isIntersecting);
        });
      }, { threshold: 0.12, rootMargin: '0px 0px -8% 0px' });
      io.observe(stage);
    }

    function teardown() {
      stop();
      audio.removeEventListener('play', start);
      audio.removeEventListener('pause', stop);
      if (io) io.disconnect();
      aura.teardown();
    }

    /* No explicit destroy hook reaches this file from sr-medplayer.js's own
       close(), so self-check on the next tick after any play/pause churn;
       already covered inside frame() via document.contains(stage). */

    return { destroy: teardown };
  }

  root.SRClearing = { mount: mount };
})(window);
