/* ============================================================================
   SafeRise -- content/galaxy.js
   prompt-galaxy-player.md -- per-protocol galaxy-cover data for the guided-
   session player (js/saferise-poster.js). Generated by tools/mk_posters.py
   from each protocol's own cover crop -- do not hand-edit; rerun the script.

   Keyed t{track}-{NN} ("t1-01"), matching content/meditation.js's MEDITATION
   key convention, not the t{track}p{no} resource-id form -- js/saferise-poster.js
   derives the key from the playing <audio>'s own src filename, so it has to
   agree with how those files are named, not with the resource store.

   flagged:true means the tonal-separation test in tools/mk_posters.py failed
   (report: prompt-galaxy-player.md #2) -- no field/subject files exist for
   that id. `cover` is always present (the existing plain crop) so
   js/saferise-poster.js can fall back to the plain cover + breath only, per
   the brief's own instruction, for a flagged id or a still-unmade audio track.
   ============================================================================ */

var GALAXY_POSTERS = {
  't0-00': { state: 'Steady', slug: 'the-clearing', startBreath: 10, cover: 'assets/coming/band-clearing.jpg', warm: [50,36,20], cool: [50,51,49], flagged: false,
    field: 'assets/galaxy/t0-00-field.jpg', clear: 'assets/galaxy/t0-00-clear.jpg', subject: 'assets/galaxy/t0-00-subject.png' },
  't1-01': { state: 'Agitated', slug: 'anxiety-reset', startBreath: 7, cover: 'assets/covers/01.jpg', warm: [50,26,9], cool: [49,60,61], flagged: true },
  't1-02': { state: 'Agitated', slug: 'anger-alchemy', startBreath: 7, cover: 'assets/covers/02.jpg', warm: [66,36,15], cool: [7,9,9], flagged: true },
  't1-03': { state: 'Agitated', slug: 'overwhelm-threshold', startBreath: 7, cover: 'assets/covers/03.jpg', warm: [120,62,22], cool: [38,63,66], flagged: true },
  't1-04': { state: 'Agitated', slug: 'abandonment-wound', startBreath: 7, cover: 'assets/covers/04.jpg', warm: [76,40,26], cool: [9,12,16], flagged: false,
    field: 'assets/galaxy/t1-04-field.jpg', clear: 'assets/galaxy/t1-04-clear.jpg', subject: 'assets/galaxy/t1-04-subject.png' },
  't1-05': { state: 'Unsteady', slug: 'shame-dissolution', startBreath: 12, cover: 'assets/covers/05.jpg', warm: [34,20,12], cool: [55,55,55], flagged: true },
  't1-06': { state: 'Unsteady', slug: 'grief-integration', startBreath: 12, cover: 'assets/covers/06.jpg', warm: [28,16,12], cool: [35,38,43], flagged: true },
  't1-07': { state: 'Numb', slug: 'shutdown-recovery', startBreath: 20, cover: 'assets/covers/07.jpg', warm: [130,83,53], cool: [36,45,56], flagged: true },
  't1-08': { state: 'Unsteady', slug: 'jealousy-release', startBreath: 12, cover: 'assets/covers/08.jpg', warm: [58,32,5], cool: [65,65,65], flagged: true },
  't1-09': { state: 'Unsteady', slug: 'insecurity-anchor', startBreath: 12, cover: 'assets/covers/09.jpg', warm: [64,42,16], cool: [65,63,61], flagged: true },
  't1-10': { state: 'Numb', slug: 'powerlessness-despair', startBreath: 20, cover: 'assets/covers/10.jpg', warm: [70,49,22], cool: [72,72,71], flagged: false,
    field: 'assets/galaxy/t1-10-field.jpg', clear: 'assets/galaxy/t1-10-clear.jpg', subject: 'assets/galaxy/t1-10-subject.png' },
  't2-01': { state: 'Agitated', slug: 'safe-conversation', startBreath: 7, cover: 'assets/covers/t2-01.jpg', warm: [76,39,17], cool: [102,98,93], flagged: true },
  't2-02': { state: 'Unsteady', slug: 'rupture-repair', startBreath: 12, cover: 'assets/covers/t2-02.jpg', warm: [139,93,50], cool: [120,123,126], flagged: true },
  't2-03': { state: 'Agitated', slug: 'trust-betrayal', startBreath: 7, cover: 'assets/covers/t2-03.jpg', warm: [166,120,82], cool: [59,61,69], flagged: true },
  't2-04': { state: 'Unsteady', slug: 'resentment-release', startBreath: 12, cover: 'assets/covers/t2-04.jpg', warm: [87,49,36], cool: [18,16,22], flagged: true },
  't2-05': { state: 'Unsteady', slug: 'intimacy-barrier', startBreath: 12, cover: 'assets/covers/t2-05.jpg', warm: [82,39,21], cool: [31,30,32], flagged: true },
  't2-06': { state: 'Unsteady', slug: 'double-standard', startBreath: 12, cover: 'assets/covers/t2-06.jpg', warm: [98,48,27], cool: [95,90,88], flagged: true },
  't2-07': { state: 'Agitated', slug: 'projection-clarity', startBreath: 7, cover: 'assets/covers/t2-07.jpg', warm: [124,65,13], cool: [104,103,102], flagged: true },
  't2-08': { state: 'Numb', slug: 'appreciation-support', startBreath: 20, cover: 'assets/covers/t2-08.jpg', warm: [131,71,40], cool: [52,47,48], flagged: true },
  't2-09': { state: 'Unsteady', slug: 'pursue-withdraw', startBreath: 12, cover: 'assets/covers/t2-09.jpg', warm: [61,41,20], cool: [63,64,63], flagged: false,
    field: 'assets/galaxy/t2-09-field.jpg', clear: 'assets/galaxy/t2-09-clear.jpg', subject: 'assets/galaxy/t2-09-subject.png' },
  't2-10': { state: 'Numb', slug: 'conscious-separation', startBreath: 20, cover: 'assets/covers/t2-10.jpg', warm: [84,55,25], cool: [87,87,87], flagged: true },
  't3-01': { state: 'Agitated', slug: 'high-stakes-presence', startBreath: 7, cover: 'assets/covers/t3-01.jpg', warm: [93,57,26], cool: [15,24,32], flagged: true },
  't3-02': { state: 'Agitated', slug: 'conflict-navigation', startBreath: 7, cover: 'assets/covers/t3-02.jpg', warm: [135,76,44], cool: [96,113,138], flagged: false,
    field: 'assets/galaxy/t3-02-field.jpg', clear: 'assets/galaxy/t3-02-clear.jpg', subject: 'assets/galaxy/t3-02-subject.png' },
  't3-03': { state: 'Unsteady', slug: 'imposter-dissolution', startBreath: 12, cover: 'assets/covers/t3-03.jpg', warm: [77,45,32], cool: [57,67,74], flagged: true },
  't3-04': { state: 'Agitated', slug: 'perfectionism-release', startBreath: 7, cover: 'assets/covers/t3-04.jpg', warm: [135,78,30], cool: [166,163,161], flagged: true },
  't3-05': { state: 'Agitated', slug: 'performance-anxiety', startBreath: 7, cover: 'assets/covers/t3-05.jpg', warm: [223,141,87], cool: [131,153,165], flagged: false,
    field: 'assets/galaxy/t3-05-field.jpg', clear: 'assets/galaxy/t3-05-clear.jpg', subject: 'assets/galaxy/t3-05-subject.png' },
  't3-06': { state: 'Unsteady', slug: 'belonging-gap', startBreath: 12, cover: 'assets/covers/t3-06.jpg', warm: [102,68,33], cool: [36,48,50], flagged: true },
  't3-07': { state: 'Unsteady', slug: 'career-transition', startBreath: 12, cover: 'assets/covers/t3-07.jpg', warm: [103,72,44], cool: [68,84,91], flagged: false,
    field: 'assets/galaxy/t3-07-field.jpg', clear: 'assets/galaxy/t3-07-clear.jpg', subject: 'assets/galaxy/t3-07-subject.png' },
  't3-08': { state: 'Numb', slug: 'decision-fatigue', startBreath: 20, cover: 'assets/covers/t3-08.jpg', warm: [226,114,52], cool: [31,176,228], flagged: false,
    field: 'assets/galaxy/t3-08-field.jpg', clear: 'assets/galaxy/t3-08-clear.jpg', subject: 'assets/galaxy/t3-08-subject.png' },
  't3-09': { state: 'Numb', slug: 'burnout-overload', startBreath: 20, cover: 'assets/covers/t3-09.jpg', warm: [88,60,29], cool: [96,96,96], flagged: false,
    field: 'assets/galaxy/t3-09-field.jpg', clear: 'assets/galaxy/t3-09-clear.jpg', subject: 'assets/galaxy/t3-09-subject.png' },
  't3-10': { state: 'Unsteady', slug: 'creative-flow', startBreath: 12, cover: 'assets/covers/t3-10.jpg', warm: [170,104,38], cool: [137,136,135], flagged: false,
    field: 'assets/galaxy/t3-10-field.jpg', clear: 'assets/galaxy/t3-10-clear.jpg', subject: 'assets/galaxy/t3-10-subject.png' }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GALAXY_POSTERS: GALAXY_POSTERS };
}
