/* ======================================================================
   SafeRise — content/inventory.js
   SR-253 · GENERATED by tools/build-inventory.py. Do not hand-edit.

   Which resource types each track actually has, derived from the authored
   files (content/t1|t2|t3-resources.js), which are the authoritative
   inventory. SHARED.resources is a PRESENTATION table keyed by these types
   and cannot decide what exists — a missing row fails loudly where a missing
   type used to under-report silently.

   Checked in rather than derived at runtime: the authored files total ~913 KB
   of resource bodies and no page should load them to learn a type list.
   Regenerate whenever they are regenerated; the standing invariant re-checks it.

   Track 03 carries ELEVEN types — it adds `raising` (Raising It). Tracks 01
   and 02 carry ten. There is no single library size across the three.
   ====================================================================== */

var RESOURCE_ORDER = ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'raising', 'repair', 'record', 'accountability'];

var RESOURCE_INVENTORY = {
  1: ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'repair', 'record', 'accountability'],
  2: ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'repair', 'record', 'accountability'],
  3: ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'raising', 'repair', 'record', 'accountability']
};

/* Per-protocol type lists — the conditionals are already resolved here, so a
   consumer never re-derives them from extras and cannot disagree with the
   authored content. */
var PROTOCOL_RESOURCE_TYPES = {
  't1-01': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'record', 'accountability'],
  't1-02': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'repair', 'record', 'accountability'],
  't1-03': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'record', 'accountability'],
  't1-04': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'repair', 'record', 'accountability'],
  't1-05': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'record', 'accountability'],
  't1-06': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'record', 'accountability'],
  't1-07': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'record', 'accountability'],
  't1-08': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'repair', 'record', 'accountability'],
  't1-09': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'repair', 'record', 'accountability'],
  't1-10': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'record', 'accountability'],
  't2-01': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'repair', 'record', 'accountability'],
  't2-02': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'repair', 'record', 'accountability'],
  't2-03': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'repair', 'record', 'accountability'],
  't2-04': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'repair', 'record', 'accountability'],
  't2-05': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'repair', 'record', 'accountability'],
  't2-06': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'repair', 'record', 'accountability'],
  't2-07': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'record', 'accountability'],
  't2-08': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'record', 'accountability'],
  't2-09': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'repair', 'record', 'accountability'],
  't2-10': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'record', 'accountability'],
  't3-01': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'raising', 'record', 'accountability'],
  't3-02': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'raising', 'repair', 'record', 'accountability'],
  't3-03': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'raising', 'record', 'accountability'],
  't3-04': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'raising', 'record', 'accountability'],
  't3-05': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'raising', 'record', 'accountability'],
  't3-06': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'raising', 'record', 'accountability'],
  't3-07': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'raising', 'record', 'accountability'],
  't3-08': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'raising', 'record', 'accountability'],
  't3-09': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory', 'disclosure', 'raising', 'record', 'accountability'],
  't3-10': ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'disclosure', 'raising', 'record', 'accountability']
};

/* Counts at generation: track type totals {1: 10, 2: 10, 3: 11}; library 276 pages. */

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { RESOURCE_ORDER: RESOURCE_ORDER,
                     RESOURCE_INVENTORY: RESOURCE_INVENTORY,
                     PROTOCOL_RESOURCE_TYPES: PROTOCOL_RESOURCE_TYPES };
}
