#!/usr/bin/env python3
"""SR-253 — generate content/inventory.js from the authored resource files.

The authored files are the authoritative inventory: they carry all eleven
resource types and T*_PROTOCOL_KEYS records which types each protocol has.
`SHARED.resources` is a PRESENTATION table and must not decide what exists.

This is the derivation. Re-run it whenever the authored files are regenerated,
and verify with the standing invariant in docs/fix-register.md — the generated
file is checked in so pages need not load 913 KB of resource bodies to learn
which types a track has.

    python3 tools/build-inventory.py            # write content/inventory.js
    python3 tools/build-inventory.py --check    # verify, exit 1 on drift
"""
import re, sys, os, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'content', 'inventory.js')

# Canonical display order. Taken from the authored key order on a protocol that
# carries all eleven (t3-02) — not invented here.
ORDER = ['meditation', 'crisiscard', 'guide', 'companion', 'practice', 'advisory',
         'disclosure', 'raising', 'repair', 'record', 'accountability']


def read_tracks():
    tracks = {}
    per_protocol = {}
    for t in (1, 2, 3):
        path = os.path.join(ROOT, 'content', 't%d-resources.js' % t)
        b = open(path, encoding='utf-8').read()
        m = re.search(r'var T%d_PROTOCOL_KEYS = \{(.*?)\n\};' % t, b, re.S)
        if not m:
            raise SystemExit('T%d_PROTOCOL_KEYS not found in %s' % (t, path))
        types = []
        for pid, keys in re.findall(r'"(t\d-\d\d)":\s*\{[^}]*keys:\s*\[(.*?)\]', m.group(1), re.S):
            ks = [k.rsplit('-', 1)[1] for k in re.findall(r'"([^"]+)"', keys)]
            per_protocol[pid] = ks
            for k in ks:
                if k not in types:
                    types.append(k)
        unknown = [k for k in types if k not in ORDER]
        if unknown:
            raise SystemExit('unknown resource type(s) %r on track %d — ORDER must be '
                             'extended deliberately, not silently' % (unknown, t))
        tracks[t] = [k for k in ORDER if k in types]
    return tracks, per_protocol


def render(tracks, per_protocol):
    counts = {t: len(v) for t, v in tracks.items()}
    total = sum(len(v) for v in per_protocol.values())
    lines = []
    lines.append('/* ' + '=' * 70)
    lines.append('   SafeRise — content/inventory.js')
    lines.append('   SR-253 · GENERATED by tools/build-inventory.py. Do not hand-edit.')
    lines.append('')
    lines.append('   Which resource types each track actually has, derived from the authored')
    lines.append('   files (content/t1|t2|t3-resources.js), which are the authoritative')
    lines.append('   inventory. SHARED.resources is a PRESENTATION table keyed by these types')
    lines.append('   and cannot decide what exists — a missing row fails loudly where a missing')
    lines.append('   type used to under-report silently.')
    lines.append('')
    lines.append('   Checked in rather than derived at runtime: the authored files total ~913 KB')
    lines.append('   of resource bodies and no page should load them to learn a type list.')
    lines.append('   Regenerate whenever they are regenerated; the standing invariant re-checks it.')
    lines.append('')
    lines.append('   Track 03 carries ELEVEN types — it adds `raising` (Raising It). Tracks 01')
    lines.append('   and 02 carry ten. There is no single library size across the three.')
    lines.append('   ' + '=' * 70 + ' */')
    lines.append('')
    lines.append('var RESOURCE_ORDER = ' + repr(ORDER).replace("'", "'") + ';')
    lines.append('')
    lines.append('var RESOURCE_INVENTORY = {')
    for t in (1, 2, 3):
        lines.append('  %d: [%s],' % (t, ', '.join("'%s'" % k for k in tracks[t])))
    lines[-1] = lines[-1].rstrip(',')
    lines.append('};')
    lines.append('')
    lines.append('/* Per-protocol type lists — the conditionals are already resolved here, so a')
    lines.append('   consumer never re-derives them from extras and cannot disagree with the')
    lines.append('   authored content. */')
    lines.append('var PROTOCOL_RESOURCE_TYPES = {')
    for pid in sorted(per_protocol):
        lines.append("  '%s': [%s]," % (pid, ', '.join("'%s'" % k for k in per_protocol[pid])))
    lines[-1] = lines[-1].rstrip(',')
    lines.append('};')
    lines.append('')
    lines.append('/* Counts at generation: track type totals %s; library %d pages. */'
                 % (counts, total))
    lines.append('')
    lines.append('if (typeof module !== \'undefined\' && module.exports) {')
    lines.append('  module.exports = { RESOURCE_ORDER: RESOURCE_ORDER,')
    lines.append('                     RESOURCE_INVENTORY: RESOURCE_INVENTORY,')
    lines.append('                     PROTOCOL_RESOURCE_TYPES: PROTOCOL_RESOURCE_TYPES };')
    lines.append('}')
    return '\n'.join(lines) + '\n'


tracks, per_protocol = read_tracks()
text = render(tracks, per_protocol)

if '--check' in sys.argv:
    cur = open(OUT, encoding='utf-8').read() if os.path.isfile(OUT) else ''
    if cur != text:
        print('DRIFT: content/inventory.js does not match the authored files. '
              'Run tools/build-inventory.py')
        sys.exit(1)
    print('inventory OK — tracks %s, library %d pages'
          % ({t: len(v) for t, v in tracks.items()}, sum(len(v) for v in per_protocol.values())))
else:
    open(OUT, 'w', encoding='utf-8').write(text)
    print('wrote %s' % OUT)
    print('  track type counts :', {t: len(v) for t, v in tracks.items()})
    print('  library pages     :', sum(len(v) for v in per_protocol.values()))
    print('  track 3 types     :', tracks[3])
